# TARGET = infinit limit celsius2fah far2celsius charNumber test ddd
# TARGET2 = triangle triangle2 arithemectics increment literal genderRatio compare compare2 sizeof oddeven fourBit fourBit2 test
# TARGET3 = 

#  all : ${TARGET}
#  all : ${TARGET2}
# all : ${TARGET3}

# infinit : $@
# limit : $@ 
# celsius2fah : $@
# far2celsius : $@
# charNumber : $@
# test : $@
# ddd: $@


# triangle2: $@
# triangle: $@
# arithemectics: $@
# increment: $@
# literal: $@
# compare: $@
# compare2: $@
# sizeof: $@
# oddeven: $@
# fourBit: $@
# fourBit2: $@

# clean : 
# 	 rm ${TARGET}
# 	 rm ${TARGET2}
# 	rm ${TARGET3}
