# python:3.7.17-slim-bullseye를 기반으로 하는 이미지 생성
FROM python:3.7.10-slim

# 작업 디렉토리 설정
WORKDIR /app

# 패키지 업데이트 및 필요한 도구 설치
RUN apt-get update && apt install -y\
    gcc \
    g++ \
    libffi-dev \
    &&  rm -rf /var/lib/apt/lists/*

# 앱 코드 복사
COPY requirements.txt ./
# 의존성 설치
RUN pip install --no-cache-dir -r requirements.txt

# 필요한 패키지 설치
COPY . .

# 포트 설정
EXPOSE 5000

# 컨테이너 시작 시 실행할 명령어
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
