TARGET = swap selection bubble qsort pointerConcept endian pointer2 functionPointer voidPointer arrayPointer arrayAssignment arrayCompare 

all : ${TARGET}

swap : $@
selection:$@
bubble : $@
qsort : $@
pointerConcept: $@
endian : $@
pointer2 : $@
functionPointer: $@
voidPointer: $@
arrayPointer: $@
arrayAssignment: $@
arrayCompare : $@

clean : 
	rm ${TARGET}
