TARGET = swap selection bubble qsort pointerConcept endian pointer2 functionPointer voidPointer arrayPointer arrayAssignment arrayCompare swapFunction sumArrayFunction sumMatrixFunction sumMatrixFunction2 helloStr charPointerOperation

all : ${TARGET}

swap : $@
selection:$@
bubble : $@
qsort : $@
pointerConcept: $@
endian : $@
pointer2 : $@
functionPointer: $@
voidPointer: $@
arrayPointer: $@
arrayAssignment: $@
arrayCompare : $@
swapFunction:$@
sumArrayFunction: $@
sumMatrixFunction: $@
sumMatrixFunction2: $@
helloStr: $@
charPointerOperation : $@



clean : 
	rm ${TARGET}
