TARGET = swap selection bubble qsort pointerConcept endian pointer2 functionPointer voidPointer arrayPointer arrayAssignment arrayCompare swapFunction sumArrayFunction sumMatrixFunction sumMatrixFunction2 helloStr charPointerOperation strcatExample filePointer fileDescriptor 

all : ${TARGET}

swap : $@
selection:$@
bubble : $@
qsort : $@
pointerConcept: $@
endian : $@
pointer2 : $@
functionPointer: $@
voidPointer: $@
arrayPointer: $@
arrayAssignment: $@
arrayCompare : $@
swapFunction:$@
sumArrayFunction: $@
sumMatrixFunction: $@
sumMatrixFunction2: $@
helloStr: $@
charPointerOperation : $@
strcatExample: $@
filePointer: $@
fileDescriptor: $@

clean : 
	rm ${TARGET}
