TARGET = infinit limit celsius2fah far2celsius charNumber test 
TARGET2 = triangle triangle2 arithemectics increment literal genderRatio compare compare2 sizeof

all : ${TARGET2}

infinit : $@
limit : $@ 
celsius2fah : $@
far2celsius : $@
charNumber : $@
test : $@


triangle2: $@
triangle: $@
arithemectics: $@
increment: $@
literal: $@
compare: $@
compare2: $@
sizeof: $@

clean : 
	rm ${TARGET2}
