TARGET = infinit limit celsius2fah far2celsius charNumber test 
TARGET2 = triangle triangle2 arithemectics increment literal

all : ${TARGET2}

infinit : $@
limit : $@ 
celsius2fah : $@
far2celsius : $@
charNumber : $@
test : $@


triangle2: $@
triangle: $@
arithemectics: $@
increment: $@
literal: $@


clean : 
	rm ${TARGET2}
