TARGET = absolute leafYear passFail grade grade2 posZeroNeg bigletter one2Ten one2tensum meand multiplyTable ascii star

all : ${TARGET}

absolute : $@
leafYear: $@
passFail: $@
grade: $@
grade2: $@
posZeroNeg:$@
bigletter:$@
one2Ten:$@
one2tensum:$@
meand:$@
multiplyTable: $@
ascii: $@
star:$@

clean : 
	rm ${TARGET}
