TARGET = absolute leafYear passFail grade grade2 posZeroNeg bigletter one2Ten one2tensum meand multiplyTable ascii star one2TenWhile one2TenDoWhile randomTwonit staticLocalVariable functionSum returnValue power dice sumArray sumMartix

all : ${TARGET}

absolute : $@
leafYear: $@
passFail: $@
grade: $@
grade2: $@
posZeroNeg:$@
bigletter:$@
one2Ten:$@
one2tensum:$@
meand:$@
multiplyTable: $@
ascii: $@
star:$@
one2TenWhile:$@
one2TenDoWhile:$@
randomTwonit:$@
staticLocalVariable: $@
functionSum: $@
returnValue:$@
power: $@
dice: $@
sumArray: $@
sumMartix:$@

clean : 
	rm ${TARGET}
